title: mega
author: Ignacio E. Losiggio
email: iglosiggio@gmail.com
description: >
  Notas personales, reflexiones, computadoras y depresión
  
twitter_username: memepowered
github_username: iglosiggio

theme: minima
